version: '3'

services:
  jenkins:
    build: . 
    hostname: jenkins
    container_name: jenkins
    restart: always
    user: root
    networks:
      - web
    volumes:
      - vol-jenkins-content:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
# -------------------------------------------------

  gitea:
    image: gitea/gitea:1.17.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - web
    labels:
      - "traefik.http.routers.gitea.rule=Host(`gitea.localhost`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    volumes:
      - ./git_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - web
    volumes:
      - ./mysql:/var/lib/mysql
# --------------------------------------------------
  registry:
    image: registry:2
    hostname: registry
    container_name: registry
    networks:
      - web
    restart: always
    labels:
      - "traefik.http.routers.registry.rule=Host(`registry.localhost`)"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
    environment:
      - REGISTRY_AUTH=$REGISTRY_AUTH
      - REGISTRY_AUTH_HTPASSWD_REALM=$REGISTRY_AUTH_HTPASSWD_REALM
      - REGISTRY_AUTH_HTPASSWD_PATH=$REGISTRY_AUTH_HTPASSWD_PATH
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=$REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
    volumes:
      - ./auth:/auth
      - ./data:/data
# ----------------------------------------------------
  traefik:
    image: "traefik:latest"
    container_name: traefik
    networks:
      - web
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "3000:3000"
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
# ------------------------------------------------------


volumes:
  vol-jenkins-content: {}


networks:
  web:
    name: web0
    external: true
